spring:
  profiles:
    active: dev
#  datasource:
#    url: jdbc:h2:mem:tradedb;DB_CLOSE_DELAY=-1
#  h2:
#    console:
#      enabled: true
#  jpa:
#    hibernate:
#      ddl-auto: validate

tradeninja:
  proxy:
    hosts:
      - 'https://bittrex.com/'
      - 'https://www.bitfinex.com/'